FROM node:alpine

#RUN mkdir -p /opt/app
#COPY package.json /opt/app/package.json
#RUN cd /opt/app && npm install

WORKDIR /opt/app
#COPY ./ /opt/app
#RUN npm install

EXPOSE 3000

ENTRYPOINT [ "npm", "start" ]
